<a href="https://colab.research.google.com/github/MihaelaHudisteanu/PMP-2024/blob/main/Tema04_PMP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Ex. 1.
Arătaţi echivalenţa dată în exemplul de la pagina 15 a cursului 3. Mai precis, arătaţi că dacă $𝐴$, $𝐵$ şi $𝐶$ sunt variabile aleatoare discrete, atunci

$𝐴 \perp 𝐶 \mid 𝐵$

dacă şi numai dacă există două funcţii pozitive $𝜙_{𝐴,𝐵}$, $𝜙_{𝐵,𝐶}$ şi o constantă de normalizare $𝑘 > 0$ astfel încât

$$𝑃(𝐴 = 𝑥_𝐴, 𝐵 = 𝑥_𝐵,𝐶 = 𝑥_𝐶) =\frac{1}{𝑘} 𝜙_{𝐴,𝐵}(𝑥_𝐴, 𝑥_𝐵)𝜙_{𝐵,𝐶}(𝑥_𝐵, 𝑥_𝐶), \forall 𝑥_𝐴, 𝑥_𝐵, 𝑥_𝐶.$$


###Solutie
"$\Longrightarrow$"

Presupunem ca $A \perp C \mid B$ si aratam ca distributia comuna poate fi scrisa in forma factorizata.


Avand $A \perp C \mid B$, stim ca:
$$
P(A, C \mid B) = P(A \mid B) \cdot P(C \mid B).
$$
Distributia comuna devine:
$$
P(A = x_A, B = x_B, C = x_C) = P(B = x_B) \cdot P(A = x_A, C = x_C \mid B = x_B)
$$
$$
=  P(B = x_B) \cdot P(A = x_A \mid B = x_B) \cdot P(C = x_C \mid B = x_B).
$$

Consideram functiile pozitive $\phi_{A,B}(x_A, x_B) = P(A = x_A, B = x_B) = P(B = x_B) \cdot P(A = x_A \mid B = x_B)$ si $\phi_{B,C}(x_B, x_C) = P(C = x_C \mid B = x_B)$, si constanta de normalizare $k = 1 > 0$. Astfel avem ca:
$$
P(A = x_A, B = x_B, C = x_C) = \frac{1}{k} \phi_{A,B}(x_A, x_B) \phi_{B,C}(x_B, x_C).
$$


"$\Longleftarrow$"

Presupunem ca exista doua functii pozitive $\phi_{A,B}$, $\phi_{B,C}$ si o constanta de normalizare $k > 0$ astfel incat:
$$
P(A = x_A, B = x_B, C = x_C) = \frac{1}{k} \phi_{A,B}(x_A, x_B) \cdot \phi_{B,C}(x_B, x_C), \ \forall x_A, x_B, x_C.
$$

Sa demonstram ca $A \perp C \mid B$.

Vom merge prin echivalente:

$$
A \perp C \mid B \Longleftrightarrow P(A, C \mid B) = P(A \mid B) \cdot P(C \mid B) \Longleftrightarrow \frac{P(A, B, C)}{P(B)} = \frac{P(A, B)}{P(B)} \cdot \frac{P(B, C)}{P(B)}
\Longleftrightarrow $$
$$
 P(A = x_A, B = x_B, C = x_C) = \frac{P(A = x_A, B = x_B) \cdot P(B = x_B, C = x_C)}{P(B = x_B)}, \forall x_A, x_B, x_C \textbf{(1)}
$$

Cum $\{x_A \cap x_B \cap x_C' \mid x_C' \in C\}$ formeaza o partitie pentru $x_A \cap x_B$, avem ca:

$$
P(A = x_A, B = x_B) = \sum_{x_C'} P(A = x_A, B = x_B, C = x_C')
$$

In mod analog avem ca:

$$
P(B = x_B, C = x_C) = \sum_{x_A'} P(A = x_A', B = x_B, C = x_C)
$$

$$
P(B = x_B) = \sum_{x_A'} \sum_{x_C'} P(A = x_A', B = x_B, C = x_C')
$$

Folosim ca $P(A = x_A, B = x_B, C = x_C) = \frac{1}{k} \phi_{A,B}(x_A, x_B) \cdot \phi_{B,C}(x_B, x_C), \forall x_A, x_B, x_C$ si inlocuim in relatia $\textbf{(1)}$:

$$
\frac{1}{k} \phi_{A,B}(x_A, x_B) \cdot \phi_{B,C}(x_B, x_C) = \frac{\sum_{x_C'} \frac{1}{k} \phi_{A,B}(x_A, x_B) \phi_{B,C}(x_B, x_C') \cdot \sum_{x_A'} \frac{1}{k} \phi_{A,B}(x_A', x_B) \phi_{B,C}(x_B, x_C)}{ \sum_{x_A'} \sum_{x_C'} \frac{1}{k} \phi_{A,B}(x_A', x_B) \phi_{B,C}(x_B, x_C')}
$$


$$
\Longleftrightarrow \phi_{A,B}(x_A, x_B) \cdot \phi_{B,C}(x_B, x_C) =  \frac{\phi_{A,B}(x_A, x_B) \cdot \phi_{B,C}(x_B, x_C) \cdot \sum_{x_C'} \phi_{B,C}(x_B, x_C') \cdot \sum_{x_A'}  \phi_{A,B}(x_A', x_B) }{ \sum_{x_A'} (\phi_{A,B}(x_A', x_B) \sum_{x_C'} \phi_{B,C}(x_B, x_C'))}
$$

$$
\Longleftrightarrow \phi_{A,B}(x_A, x_B) \cdot \phi_{B,C}(x_B, x_C) =  \frac{\phi_{A,B}(x_A, x_B) \cdot \phi_{B,C}(x_B, x_C) \cdot \sum_{x_C'} \phi_{B,C}(x_B, x_C') \cdot \sum_{x_A'}  \phi_{A,B}(x_A', x_B) }{ \sum_{x_A'} \phi_{A,B}(x_A', x_B) \cdot \sum_{x_C'} \phi_{B,C}(x_B, x_C')}
$$

$$
\Longleftrightarrow \phi_{A,B}(x_A, x_B) \cdot \phi_{B,C}(x_B, x_C) =  \frac{\phi_{A,B}(x_A, x_B) \cdot \phi_{B,C}(x_B, x_C) \cdot 1 }{ 1}
$$

Relatia $\textbf{(1)}$ este adevarata, asadar $A \perp C \mid B$.

---

### Ex. 2

Considerăm o regiune în care observăm vremea la mai multe staţii meteo, \(S_1, S_2, \dots, S_n\). Fiecare staţie raportează una dintre cele trei stări: „Soare”, „Ploaie” sau „Nori”. Vrem să prezicem starea vremii la fiecare staţie meteo, luând în considerare dependenţele dintre staţiile adiacente. Considerăm că vremea la o staţie depinde direct de vremea la staţiile vecine.

Vom folosi o reţea Markoviană pentru a modela vremea la mai multe locaţii şi vom inferea asupra vremii la o staţie necunoscută, pe baza datelor de la vecini.

#### Date de intrare (introduse de către utilizator):
- Numărul de staţii meteo, \(n\);
- Muchiile corespunzătoare reţelei Markoviene, adică vecinii fiecărei staţii. Pentru simplitate, vom presupune că reţeaua este aciclică, adică nu există clici de dimensiune 3;
- Probabilităţile iniţiale pentru fiecare staţie (exemplu: \(P(S) = 0.5\), \(P(P) = 0.3\), \(P(N) = 0.2\)).

Folosind **pgmpy**, definiţi o reţea Markoviană pentru problema de mai sus, unde potenţialul pentru fiecare pereche de staţii vecine (adiacente) este dat de matricea:

\[
\begin{bmatrix}
0.7 & 0.2 & 0.1 \\
0.2 & 0.6 & 0.2 \\
0.1 & 0.3 & 0.6 \\
\end{bmatrix}
\]

Folosiţi metoda **Maximum A Posteriori (MAP)** pentru a prezice starea vremii la fiecare staţie meteo. În pgmpy, puteţi apela funcţiile `BeliefPropagation` şi `map_query`.


In [ ]:
!pip install pgmpy

In [ ]:
from pgmpy.models import MarkovNetwork
from pgmpy.factors.discrete import DiscreteFactor
from pgmpy.inference import BeliefPropagation
import numpy as np
import networkx as nx

states = ['Soare', 'Ploaie', 'Nori']

n = int(input("Numarul de statii meteo:"))

edges_input_list = input("Muchii retea Markov:").split()
edges = [('S' + edges_input_list[i],'S' + edges_input_list[i + 1]) for i in range(0, len(edges_input_list), 2)]
model = MarkovNetwork(edges)

pos = nx.circular_layout(model)
nx.draw(model, with_labels=True, pos=pos, alpha=0.5, node_size=2000)


initial_probs = []
for i in range(n):
  initial_probs_list = input(f"Probabilitati initiale pentru statia {i+1}: ").split()
  initial_probs = list(map(float, initial_probs_list))

  initial_factor = DiscreteFactor(variables=[f"S{i+1}"], cardinality=[3], values=initial_probs)
  model.add_factors(initial_factor)


potential_matrix = np.array([
    [0.7, 0.2, 0.1],
    [0.2, 0.6, 0.2],
    [0.1, 0.3, 0.6]
])

for (node1, node2) in edges:
    factor = DiscreteFactor(variables=[node1, node2], cardinality=[3, 3], values=potential_matrix.flatten())
    model.add_factors(factor)


model.get_local_independencies()

bp_infer = BeliefPropagation(model)
marginals = bp_infer.map_query(variables=[f'S{i+1}' for i in range(n)])

print("Stari prezise:")
for station, state in marginals.items():
    print(f"Stația {station}: {states[state]}")


###Ex. 3.
O problemă clasică care poate fi rezolvată folosind Markov Random Fields (MRF) este cea a denoising-ului
imaginii, unde obiectivul este de a curăţa o imagine cu zgomot (noise) prin estimarea valorii fiecărui pixel, bazându-ne
pe vecinii săi.

a) Alegeţi mai întâi o imagine de dimensiune foarte mică (de ordinul 5 × 5), pe care să o utilizaţi drept imagine
originală. Imaginea poate fi creată în mod determinist sau aleatoriu.

b) Alegeţi la întâmplare un număr de pixeli (în jur de 10%) pentru a fi modificaţi şi creaţi astfel o modificare zgomotoasă a imaginii originale.

Considerăm un grid 2D, în care fiecare nod (pixel) este conectat la cei patru vecini direcţi (N, S, E, W). Energia totală $E(x)$ a unui grid poate fi descrisă de două componente:

- O componentă care penalizează discrepanţele între variabilele observate şi cele latente.
- O componentă care penalizează discrepanţele între pixelii vecini, favorizând o imagine mai uniformă.

Funcţia de energie poate fi scrisă astfel:

$$
E(x) = \sum_{i} \lambda(x_i - y_i)^2 + \sum_{(i,j)} (x_i - x_j)^2
$$

unde

- $x_i$ este pixelul curat de estimat;
- $y_i$ este pixelul observat;
- $\lambda$ este un factor de regularizare care controlează influenţa zgomotului, ales de utilizator;
- $(i, j)$ reprezintă perechi de pixeli vecini.

c) Folosind pgmpy, definiţi o reţea Markoviană care să descrie contextul de mai sus.

d) Folosiţi metoda Maximum A Posteriori (MAP) pentru a estima imaginea originală pornind de la cea modificată (la fel ca la Ex. 2, puteţi apela funcţiile BeliefPropagation şi map_query).


In [ ]:
import numpy as np
from pgmpy.models import MarkovNetwork
from pgmpy.factors.discrete import DiscreteFactor
from pgmpy.inference import BeliefPropagation

#a)
rows = 5
cols = 5
original_image = np.array([[1, 1, 1, 0, 0],
                            [1, 1, 1, 0, 0],
                            [1, 1, 1, 0, 0],
                            [0, 0, 0, 0, 0],
                            [0, 0, 0, 0, 0]])

print("Imaginea initiala:")
print(original_image)



#b)
noisy_image = original_image.copy()
num_noisy_pixels = int(0.1 * rows * cols)
indices = np.random.choice(rows * cols, num_noisy_pixels, replace=False)

for index in indices:
    row = index // rows
    col = index % rows
    noisy_image[row, col] = 1 - noisy_image[row, col]

print("Imaginea cu zgomot:")
print(noisy_image)


model = MarkovNetwork()
for i in range(rows):
    for j in range(cols):
      model.add_node((i,j))

for i in range(rows):
    for j in range(cols):
      if i < rows - 1:
          model.add_edge((i, j), (i + 1, j))
      if j < cols - 1:
          model.add_edge((i, j), (i, j + 1))





#componentă care penalizează discrepanţele între variabilele observate şi cele latente
lambda_value = 2
for i in range(rows):
    for j in range(cols):
        observed_value = noisy_image[i, j]
        #penalizarile unare sunt adaugate separat, suma totala este calculata in timpul inferentei
        factor = DiscreteFactor(variables=[(i,j)], cardinality=[2], values = [np.exp(-lambda_value * (0 - observed_value)**2), np.exp(-lambda_value * (1 - observed_value)**2)])
        model.add_factors(factor)

#componentă care penalizează discrepanţele între pixelii vecini
for edge in model.edges():
    node1, node2 = edge
    pairwise_potential = np.array([[np.exp(-(v1 - v2) ** 2)  for v2 in range(2)] for v1 in range(2)])
    factor = DiscreteFactor(variables=[node1, node2], cardinality=[2, 2], values = pairwise_potential.flatten())
    model.add_factors(factor)


bp_infer = BeliefPropagation(model)
marginals = bp_infer.map_query(variables=[(i,j) for i in range(rows) for j in range(cols)])


cleaned_image = np.zeros((rows, cols), dtype=int)
for i in range(rows):
    for j in range(cols):
        cleaned_image[i, j] = marginals[(i,j)]

print("Imaginea curățată estimată:")
print(cleaned_image)


Imaginea initiala:
[[1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Imaginea cu zgomot:
[[1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]
Imaginea curățată estimată:
[[1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]


In [ ]:
import numpy as np
from pgmpy.models import MarkovNetwork
from pgmpy.factors.discrete import DiscreteFactor
from pgmpy.inference import BeliefPropagation

#a)
rows = 5
cols = 5
original_image = np.array([[1, 1, 1, 0, 0],
                            [1, 1, 1, 0, 0],
                            [1, 1, 1, 0, 0],
                            [0, 0, 0, 0, 0],
                            [0, 0, 0, 0, 0]])

print("Imaginea initiala:")
print(original_image)



#b)
noisy_image = original_image.copy()
num_noisy_pixels = int(0.1 * rows * cols)
indices = np.random.choice(rows * cols, num_noisy_pixels, replace=False)

for index in indices:
    row = index // rows
    col = index % rows
    noisy_image[row, col] = 1 - noisy_image[row, col]

print("Imaginea cu zgomot:")
print(noisy_image)


model = MarkovNetwork()
for i in range(rows):
    for j in range(cols):
      model.add_node((i,j))

for i in range(rows):
    for j in range(cols):
      if i < rows - 1:
          model.add_edge((i, j), (i + 1, j))
      if j < cols - 1:
          model.add_edge((i, j), (i, j + 1))





#componentă care penalizează discrepanţele între variabilele observate şi cele latente
lambda_value = 2
for i in range(rows):
    for j in range(cols):
        observed_value = noisy_image[i, j]
        #penalizarile unare sunt adaugate separat, suma totala este calculata in timpul inferentei
        factor = DiscreteFactor(variables=[(i,j)], cardinality=[2], values = [(lambda_value * (0 - observed_value)**2), (lambda_value * (1 - observed_value)**2)])
        model.add_factors(factor)

#componentă care penalizează discrepanţele între pixelii vecini
for edge in model.edges():
    node1, node2 = edge
    pairwise_potential = np.array([[((v1 - v2) ** 2)  for v2 in range(2)] for v1 in range(2)])
    factor = DiscreteFactor(variables=[node1, node2], cardinality=[2, 2], values = pairwise_potential.flatten())
    model.add_factors(factor)


bp_infer = BeliefPropagation(model)
bp_infer.calibrate()
marginals = bp_infer.map_query(variables=[(i,j) for i in range(rows) for j in range(cols)])


cleaned_image = np.zeros((rows, cols), dtype=int)
for i in range(rows):
    for j in range(cols):
        cleaned_image[i, j] = marginals[(i,j)]

print("Imaginea curățată estimată:")
print(cleaned_image)


Imaginea initiala:
[[1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Imaginea cu zgomot:
[[1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]]


/usr/local/lib/python3.10/dist-packages/pgmpy/factors/discrete/DiscreteFactor.py:797: RuntimeWarning: invalid value encountered in divide
  phi.values = phi.values / phi1.values
/usr/local/lib/python3.10/dist-packages/pgmpy/factors/discrete/DiscreteFactor.py:489: RuntimeWarning: invalid value encountered in divide
  phi.values = phi.values / phi.values.sum()


Imaginea curățată estimată:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
